export const DEV_LANGUAGE_OPTIONS = [
    { value: "javascript", label: "JavaScript" },
    { value: "typescript", label: "TypeScript" },
    { value: "html", label: "HTML" },
    { value: "css", label: "CSS" },
    { value: "scss", label: "SCSS" },
    { value: "python", label: "Python" },
    { value: "java", label: "Java" },
    { value: "kotlin", label: "Kotlin" },
    { value: "csharp", label: "C#" },
    { value: "fsharp", label: "F#" },
    { value: "go", label: "Go" },
    { value: "rust", label: "Rust" },
    { value: "php", label: "PHP" },
    { value: "ruby", label: "Ruby" },
    { value: "elixir", label: "Elixir" },
    { value: "scala", label: "Scala" },
    { value: "clojure", label: "Clojure" },
    { value: "swift", label: "Swift" },
    { value: "objective-c", label: "Objective-C" },
    { value: "dart", label: "Dart" },
    { value: "c", label: "C" },
    { value: "cpp", label: "C++" },
    { value: "assembly", label: "Assembly" },
    { value: "r", label: "R" },
    { value: "matlab", label: "MATLAB" },
    { value: "sql", label: "SQL" },
    { value: "graphql", label: "GraphQL" },
    { value: "bash", label: "Bash" },
    { value: "shell", label: "Shell scripting" },
    { value: "powershell", label: "PowerShell" },
    { value: "lua", label: "Lua" },
];
