export const FRAMEWORK_OPTIONS = [
    { value: "react", label: "React" },
    { value: "nextjs", label: "Next.js" },
    { value: "gatsby", label: "Gatsby" },
    { value: "remix", label: "Remix" },
    { value: "vue", label: "Vue.js" },
    { value: "nuxt", label: "Nuxt.js" },
    { value: "angular", label: "Angular" },
    { value: "svelte", label: "Svelte" },
    { value: "sveltekit", label: "SvelteKit" },
    { value: "solidjs", label: "SolidJS" },
    { value: "qwik", label: "Qwik" },
    { value: "preact", label: "Preact" },
    { value: "ember", label: "Ember.js" },
    { value: "backbone", label: "Backbone.js" },
    { value: "alpinejs", label: "Alpine.js" },
    { value: "jquery", label: "jQuery" },
    { value: "react-native", label: "React Native" },
    { value: "expo", label: "Expo" },
    { value: "flutter", label: "Flutter" },
    { value: "ionic", label: "Ionic" },
    { value: "nativescript", label: "NativeScript" },
    { value: "tailwindcss", label: "Tailwind CSS" },
    { value: "bootstrap", label: "Bootstrap" },
    { value: "bulma", label: "Bulma" },
    { value: "foundation", label: "Foundation" },
    { value: "semantic-ui", label: "Semantic UI" },
    { value: "mui", label: "Material UI (MUI)" },
    { value: "chakra-ui", label: "Chakra UI" },
    { value: "ant-design", label: "Ant Design" },
    { value: "shadcn-ui", label: "shadcn/ui" },
    { value: "radix-ui", label: "Radix UI" },
    { value: "headless-ui", label: "Headless UI" },
    { value: "mantine", label: "Mantine" },
    { value: "primereact", label: "PrimeReact" },
    { value: "vuetify", label: "Vuetify" },
    { value: "quasar", label: "Quasar" },
    { value: "redux", label: "Redux" },
    { value: "mobx", label: "MobX" },
    { value: "zustand", label: "Zustand" },
    { value: "recoil", label: "Recoil" },
    { value: "xstate", label: "XState" },
    { value: "pinia", label: "Pinia" },
    { value: "ngrx", label: "NgRx" },
    { value: "express", label: "Express.js" },
    { value: "nest", label: "NestJS" },
    { value: "fastify", label: "Fastify" },
    { value: "koa", label: "Koa" },
    { value: "hapi", label: "hapi" },
    { value: "adonis", label: "AdonisJS" },
    { value: "sails", label: "Sails.js" },
    { value: "strapi", label: "Strapi" },
    { value: "keystone", label: "KeystoneJS" },
    { value: "django", label: "Django" },
    { value: "flask", label: "Flask" },
    { value: "fastapi", label: "FastAPI" },
    { value: "pyramid", label: "Pyramid" },
    { value: "laravel", label: "Laravel" },
    { value: "symfony", label: "Symfony" },
    { value: "codeigniter", label: "CodeIgniter" },
    { value: "rails", label: "Ruby on Rails" },
    { value: "spring-boot", label: "Spring Boot" },
    { value: "play-framework", label: "Play Framework" },
    { value: "aspnet-core", label: "ASP.NET Core" },
    { value: "phoenix", label: "Phoenix (Elixir)" },
    { value: "gin", label: "Gin (Go)" },
    { value: "fiber", label: "Fiber (Go)" },
    { value: "jest", label: "Jest" },
    { value: "vitest", label: "Vitest" },
    { value: "mocha", label: "Mocha" },
    { value: "jasmine", label: "Jasmine" },
    { value: "karma", label: "Karma" },
    { value: "testing-library", label: "React Testing Library" },
    { value: "enzyme", label: "Enzyme" },
    { value: "cypress", label: "Cypress" },
    { value: "playwright", label: "Playwright" },
    { value: "puppeteer", label: "Puppeteer" },
    { value: "storybook", label: "Storybook" },
    { value: "vite", label: "Vite" },
    { value: "webpack", label: "Webpack" },
    { value: "rollup", label: "Rollup" },
    { value: "parcel", label: "Parcel" },
    { value: "gulp", label: "Gulp" },
    { value: "nx", label: "Nx" },
    { value: "turborepo", label: "Turborepo" },
];
