export const SOFT_SKILL_OPTIONS = [
    { value: "communication", label: "Communication" },
    { value: "verbal-communication", label: "Verbal communication" },
    { value: "written-communication", label: "Written communication" },
    { value: "active-listening", label: "Active listening" },
    { value: "nonverbal-communication", label: "Nonverbal communication" },
    { value: "presentation-skills", label: "Presentation skills" },
    { value: "public-speaking", label: "Public speaking" },
    { value: "storytelling", label: "Storytelling" },
    { value: "negotiation", label: "Negotiation" },
    { value: "persuasion", label: "Persuasion" },
    { value: "influencing", label: "Influencing others" },
    { value: "giving-feedback", label: "Giving constructive feedback" },
    { value: "receiving-feedback", label: "Receiving feedback" },
    { value: "questioning", label: "Asking clarifying questions" },
    { value: "cross-cultural-communication", label: "Cross-cultural communication" },
    { value: "teamwork", label: "Teamwork" },
    { value: "collaboration", label: "Collaboration" },
    { value: "relationship-building", label: "Relationship building" },
    { value: "interpersonal-skills", label: "Interpersonal skills" },
    { value: "empathy", label: "Empathy" },
    { value: "emotional-intelligence", label: "Emotional intelligence" },
    { value: "conflict-resolution", label: "Conflict resolution" },
    { value: "mediation", label: "Mediation" },
    { value: "diplomacy", label: "Diplomacy" },
    { value: "patience", label: "Patience" },
    { value: "approachability", label: "Approachability" },
    { value: "respectfulness", label: "Respectfulness" },
    { value: "networking", label: "Networking" },
    { value: "relationship-management", label: "Relationship management" },
    { value: "leadership", label: "Leadership" },
    { value: "people-management", label: "People management" },
    { value: "team-management", label: "Team management" },
    { value: "team-leadership", label: "Team leadership" },
    { value: "delegation", label: "Delegation" },
    { value: "coaching", label: "Coaching" },
    { value: "mentoring", label: "Mentoring" },
    { value: "motivating-others", label: "Motivating others" },
    { value: "performance-management", label: "Performance management" },
    { value: "conflict-management", label: "Conflict management" },
    { value: "change-management", label: "Change management" },
    { value: "stakeholder-management", label: "Stakeholder management" },
    { value: "decision-making", label: "Decision making" },
    { value: "accountability", label: "Accountability" },
    { value: "ownership", label: "Ownership" },
    { value: "problem-solving", label: "Problem solving" },
    { value: "analytical-thinking", label: "Analytical thinking" },
    { value: "critical-thinking", label: "Critical thinking" },
    { value: "creative-thinking", label: "Creative thinking" },
    { value: "innovation", label: "Innovation" },
    { value: "troubleshooting", label: "Troubleshooting" },
    { value: "root-cause-analysis", label: "Root cause analysis" },
    { value: "systems-thinking", label: "Systems thinking" },
    { value: "strategic-thinking", label: "Strategic thinking" },
    { value: "data-informed-decisions", label: "Data-informed decision making" },
    { value: "judgement", label: "Sound judgment" },
    { value: "time-management", label: "Time management" },
    { value: "organisation", label: "Organizational skills" },
    { value: "planning", label: "Planning" },
    { value: "prioritisation", label: "Prioritization" },
    { value: "scheduling", label: "Scheduling" },
    { value: "multitasking", label: "Multitasking" },
    { value: "attention-to-detail", label: "Attention to detail" },
    { value: "focus", label: "Focus" },
    { value: "self-discipline", label: "Self-discipline" },
    { value: "self-motivation", label: "Self-motivation" },
    { value: "self-direction", label: "Self-direction" },
    { value: "independence", label: "Working independently" },
    { value: "reliability", label: "Reliability" },
    { value: "dependability", label: "Dependability" },
    { value: "punctuality", label: "Punctuality" },
    { value: "follow-through", label: "Follow-through" },
    { value: "adaptability", label: "Adaptability" },
    { value: "flexibility", label: "Flexibility" },
    { value: "resilience", label: "Resilience" },
    { value: "stress-management", label: "Stress management" },
    { value: "working-under-pressure", label: "Working under pressure" },
    { value: "openness-to-change", label: "Openness to change" },
    { value: "learning-from-feedback", label: "Learning from feedback" },
    { value: "growth-mindset", label: "Growth mindset" },
    { value: "curiosity", label: "Curiosity" },
    { value: "willingness-to-learn", label: "Willingness to learn" },
    { value: "initiative", label: "Initiative" },
    { value: "proactivity", label: "Proactivity" },
    { value: "resourcefulness", label: "Resourcefulness" },
    { value: "result-orientation", label: "Results orientation" },
    { value: "ownership-mindset", label: "Ownership mindset" },
    { value: "work-ethic", label: "Strong work ethic" },
    { value: "professionalism", label: "Professionalism" },
    { value: "integrity", label: "Integrity" },
    { value: "honesty", label: "Honesty" },
    { value: "discretion", label: "Discretion" },
    { value: "customer-service", label: "Customer service" },
    { value: "client-focus", label: "Client focus" },
    { value: "user-focus", label: "User-centric mindset" },
    { value: "service-orientation", label: "Service orientation" },
    { value: "complaint-handling", label: "Complaint handling" },
    { value: "de-escalation", label: "De-escalation" },
    { value: "rapport-building", label: "Rapport building" },
    { value: "remote-collaboration", label: "Remote collaboration" },
    { value: "async-communication", label: "Asynchronous communication" },
    { value: "cross-functional-collaboration", label: "Cross-functional collaboration" },
    { value: "knowledge-sharing", label: "Knowledge sharing" },
]